name: text2img
channels:
    - pytorch
    - nvidia
    - defaults
    - anaconda
    - conda-forge
dependencies:
    - python=3.10
    - tqdm
    - libnvjpeg=11.8
    - conda-forge::openssl
    - numpy=1.26.4
    - pytorch=2.2.1
    - torchvision=0.17.1
    - torchtext=0.17.1
    - pytorch-cuda=11.8
    - pip
    - matplotlib
    - chardet
    - timm
    - scipy==1.10.1
    - pyparsing
    - pycocotools
    - pip:
        - discord-webhook>=1.2.1
        - clean-fid
