name: text2img
channels:
    - pytorch
    - nvidia
    - defaults
    - anaconda
dependencies:
    - python=3.10
    - tqdm
    - libnvjpeg>12.0
    - conda-forge::openssl
    - numpy=1.26.4
    - pytorch=2.5.1
    - torchvision=0.20.1
    - torchtext
    - pytorch-cuda=12.4
    - pip
    - matplotlib
    - chardet
    - timm
    - scipy
    - pyparsing
    - pycocotools
    - tensorboard
    - pip:
        - discord-webhook
        - clean-fid
